version: '3.8'

services:
  # Using PostgreSQL as GaussDB is PostgreSQL-compatible
  # In production, this would be replaced with actual GaussDB/OpenGauss
  gaussdb:
    image: opengauss/opengauss-server:latest
    container_name: diesel-gaussdb-test
    environment:
      POSTGRES_USER: gaussdb
      POSTGRES_PASSWORD: Gaussdb@123
      POSTGRES_DB: diesel_test
      GS_PASSWORD: Gaussdb@123
    volumes:
      - gaussdb-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "su - omm -c 'gsql -d postgres -p 5432 -c \"SELECT 1;\"' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  gaussdb-data:
